### ISSUE TITLE
[Bug] Stepping through a one line function in a array doesn't step through each iteration and breaks.

### ISSUE THREAD

**Issue by mrpatches123** [Mojang/minecraft-debugger#10]
every time I step through
```js
const test = [];
const array = Array.from(Array(256), (item, i) => ({ x: i % 16, z: Math.floor(i / 16) % 16 }))
  .filter(({ x, z }) => {
    const entities = overworld.getEntitiesAtBlockLocation(new BlockLocation(x, -64, z));
    test.shift(entities.length);
    return Boolean(entities.length);
});
```

it does not step through each iteration of the map function in the Array.from like node.js does, but it does not hang up. Contrastly, when it reaches the filter it doesn't hang up but doesn't step through each iteration, and undefined shows in the debug console.

**Comment by chmeyer-ms** [comment]
I believe this has been addressed with recent updates to QuickJS and the debugger.  I ran the provided snippet and it does respect breakpoints set in the filter function. This may be somewhat different from V8/node but should be workable.
