### ISSUE TITLE
Minecraft Command Shortcuts Not Working

### ISSUE THREAD

**Issue by DauntlessStudio** [Mojang/minecraft-debugger#239]
Howdy, when trying to run a command via the new Minecraft Shortcut Commands option, nothing seems to happen. I have the extension set up correctly and am connected to Minecraft, I can see my scripting logs appearing in the Debug Console, and the Diagnostics panel is working, just the command shortcuts aren't.
Is this a feature that requires a later version of Minecraft than 1.21.31? Or is more configuration required that hasn't been documented yet, or I missed somewhere?

**Comment by JakeShirley** [comment]
The commands pane only works on Minecraft versions 1.21.50 preview or higher.  Sorry for not documenting that!
