### ISSUE TITLE
Object.entries(object).forEach breaks the debugger 

### ISSUE THREAD

**Issue by mrpatches123** [Mojang/minecraft-debugger#24]
code
```js
const object = { help: 8, heloo: 9, hejkekj: 8 };
Object.entries(object).forEach(([key, value]) => {
	console.warn(JSON.stringify({ [key]: value }));
});
```

error:
Failed to get stack trace for undefined at line undefined.

in-game the code works fine

**Comment by xiller228** [comment]
its bug also occurs on any array methods with callbacks

code to test:
```js
const array = [0, 1, 2, 3];

array.map((el) => {
	if (typeof el === "number") return el;
});

array.filter((e) => typeof e === "number");

array.forEach((e) => {
	e++;
});

array.find((e) => {
	if (e.toFixed) return e;
});
```
debugger console output:
![photo](https://user-images.githubusercontent.com/110915645/204106155-62229d5c-d9a2-4eef-8dbd-9a0de654ea34.png)

**Comment by mrpatches123** [comment]
What's weird is callbacks in custom functions (prototypes) do not throw but only native array ones.

**Comment by chmeyer-ms** [comment]
Closing, I tested the snippet and it appears to work.  Likely fixed with updates to QuickJS.

**Comment by leaftail1880** [comment]
yep, it works now! Thanks!
