### ISSUE TITLE
Cant Debug Typescript

### ISSUE THREAD

**Issue by ronny130286** [Mojang/minecraft-debugger#27]
Hello,

you cant use debugger with typescript. I add the sourceMapRoot and generatedSourceRoot to the launch.json, but every time you connect to the debugger i got this message:

`Failed to find source files. Check that launch.json 'localRoot' contains scripts or if using source maps that 'sourceMapRoot' is correct.`

**Comment by ThomasOrs** [comment]
#28 should resolve this I believe.

**Comment by mammerla** [comment]
(sorry for the delayed response).  There have been a few updates since this time, and the readme has been updated as well. If this still reproduces with updated launch.json configs, please re-open!
