### ISSUE TITLE
Cannot debug files within subfolders using sourcemap

### ISSUE THREAD

**Issue by hyperbeem** [Mojang/minecraft-debugger#30]
**Source mapping debugging ignores subfolders when debugging.** 

When using source map, only the top level of .js files are read, even though subfolders containing valid .js and .map files exist as only the top level of the source files are read as there is not logic to search sub folders. The following output comes from within the `doFilesWithExtExistAt` function (ln 578:Session.ts), showing that a folder is present, but not searched (events).

![Code_SQWZBFYM4i](https://user-images.githubusercontent.com/876699/224848767-67a30e76-d2c0-4911-b33a-64232f99d668.png)

Any project with organisation, such as placing event files within the even folder will be skipped and cannot be debugged. Although this may be non typescript like; this will help with organisation for large scripting projects when using source mapping.

**Comment by ThomasOrs** [comment]
This is no longer an issue in `1.4.0` of the extension. Resolved in #28.
