### ISSUE TITLE
README Instructions Not Fully Correct

### ISSUE THREAD

**Issue by DauntlessStudio** [Mojang/minecraft-debugger#57]
The README section `Prepare Visual Studio for a connection` has the launch.json example:
```json
{
  "version": "0.3.0",
  "configurations": [
    {
      "type": "minecraft-js",
      "request": "attach",
      "name": "Debug with Minecraft",
      "mode": "connect",
      "preLaunchTask": "build",
      "targetModuleUuid": "7c7e693f-99f4-41a9-95e0-1f57b37e1e12",
      "localRoot": "${workspaceFolder}/",
      "port": 19144
   }
  ]
}
```
Then the following section `Run your Minecraft Behavior Pack` says to use the command `script debugger connect`.

This doesn't quite work, the launch.json should instead say `"mode": "listen"` if VSCode is supposed to await a connection.

**Comment by JakeShirley** [comment]
Thanks for the report!
