### ISSUE TITLE
Minecraft Diagnostics tab blank

### ISSUE THREAD

**Issue by gbaman** [Mojang/minecraft-debugger#83]
Minecraft Bedrock version : v1.21.2
Extension version - v1.7.0

With a (TS) script running, both the RP and BP attached to a world and running within that world, when I run `/script debugger connect` it connects fine and breakpoints work as expected. What doesn't work though is the new Minecraft Diagnostics tab, which has always been blank for me, like nothing is connected?

Is there any extra magic hoops to jump through to get it working? I've got my launch.json below. It comes straight from the TS starter project and I've only got a single RP and BP loaded.

```json
{
    "version": "0.2.0",
    "configurations": [
      {
        "type": "minecraft-js",
        "request": "attach",
        "name": "Debug with Minecraft",
        "mode": "listen",
        "preLaunchTask": "build",
        "sourceMapRoot": "${workspaceFolder}/dist/debug/",
        "generatedSourceRoot": "${workspaceFolder}/dist/scripts/",
        "port": 19144
      }
    ]
  }
```

![image](https://github.com/user-attachments/assets/e778f959-ca67-484f-a5cf-5c028a50b56e)

**Comment by JakeShirley** [comment]
Bad version handling on our part here but unlikely to go back and fix.

The Diagnostics window requires Minecraft 1.21.10 or higher (currently on 1.21.20 public previews).  You're in 1.21.2 (_not_ 1.21.20), so it won't have the required stuff to show the diagnostics.

The version requirement is noted here, albeit not super clearly.  https://github.com/Mojang/minecraft-debugger/?tab=readme-ov-file#diagnostics-window
