### ISSUE TITLE
Very troublesome user experience

### ISSUE THREAD

**Issue by tryashtar** [Mojang/minecraft-debugger#87]
Hi there. Once I got this extension finally working, it was very pleasant. But _wow_, I have never seen an extension take so many steps to get working!!

The readme is helpful, but opening a powershell terminal, pasting in the most bizarre random command I've ever seen (pasting random commands from the internet, very secure and recommended practice right?), configuring a JSON file, copying a UUID from my manifest into VSCode, starting a debug session, then finally running a command in-game was not a fun time! And believe me that the errors you get if you miss a step, if they exist at all, aren't super helpful. I'd be hard-pressed to remember all of those steps just to debug a small issue on a random test world.

I'd like to live in a world where this extension works totally out of the box. You open minecraft and vscode, and the diagnostics tab works right away. You open your pack folder and set a breakpoint, and it hits. No weird commands or finicky configuration except in unusual setups. Just a bit of feedback from a grateful but frazzled user. 🙂

**Comment by JakeShirley** [comment]
Definitely good feedback.

A few things are in the pipe around helping the developer know if something is misconfiguration or get the connection configured more easily.

Unfortunately TypeScript + source maps will always introduce a little bit more complexity due to how different build steps are, but that doesn't mean we should strive for easy of use.

**Comment by MKokeshi** [comment]
It sounds like you're discussing an extension for debugging Minecraft, specifically in the context of working with Minecraft Bedrock Edition add-ons or possibly modding tools. From your description, this likely involves setting up a development environment in Visual Studio Code (VSCode) to debug Minecraft scripts, which can indeed be a complex process.

### Here's a breakdown of what you're likely experiencing:

1. **PowerShell Command**: This step usually involves setting up your development environment, possibly installing dependencies, or configuring your Minecraft instance to work with VSCode. Running a command in PowerShell can be daunting, especially if it seems arcane or isn't well-documented.

2. **Configuring JSON Files**: This likely refers to setting up the `launch.json` file in VSCode, which configures how the debugger will connect to Minecraft. You might need to specify things like the version of Minecraft you're using, the path to your mod/add-on, and other environment details.

3. **UUID and Manifest**: UUIDs are used in Minecraft Bedrock Edition add-ons to uniquely identify them. Copying this UUID into VSCode probably helps the debugger know which add-on to attach to.

4. **Debug Session and In-Game Commands**: After setting up everything, you need to start a debug session in VSCode, which then attaches to the running Minecraft instance. Running a command in-game is often the final step to trigger the debugger, such as loading the specific add-on or executing the code you want to debug.

### Feedback and Simplification

The steps you've outlined are fairly typical for setting up a complex debugging environment, but they can indeed be overwhelming, especially if the process isn't well-documented or if errors are cryptic.

Your feedback about the setup process highlights the need for better automation and clearer documentation. Ideally, a streamlined setup process could involve:
- **Automated Setup**: A script or tool that automates the PowerShell command, UUID configuration, and JSON setup would save a lot of hassle.
- **Improved Documentation**: Step-by-step guides with screenshots or videos could help users understand what each step does and why it's necessary.
- **Error Handling**: More informative error messages or even a diagnostic tool that checks your setup could make troubleshooting easier.

### What Can Be Done?
  
- **Community Resources**: Sometimes, the community around such tools will create simplified guides or scripts to help automate the setup. Checking forums, GitHub issues, or other user-contributed content might provide easier solutions.

- **Automation Ideas**: If you're familiar with scripting, you might consider creating a batch script or PowerShell script that automates the most painful parts of the setup for your future projects.

It's clear that while the extension provides powerful functionality, the initial setup is a barrier. Your feedback is valuable and highlights a common issue in many development tools: balancing power with ease of use.

**Comment by tryashtar** [comment]
Can we not clog this issue with crappy AI spam please?

**Comment by JakeShirley** [comment]
FYI the latest release adds the ability to pick the pack you're debugging when you go to attach the debugger.  This should really help with the "copy this random UUID" scenario.

**Comment by chmeyer-ms** [comment]
Latest VSCode extension has some usability improvements, including a prompt for the target pack and additional logging. Keep in mind that this will require waiting for the next release of MC. If you can think of anything else that would make on-boarding easier, please let us know.  Closing this issue and thanks for the feedback.
